### ISSUE TITLE
Apps not available on play store

### ISSUE THREAD

**Issue by Swati4star** [pcqpcq/open-source-android-apps#144]
Two apps listed in Multimedia category :
[Anime Taste](https://play.google.com/store/apps/details?id=com.zhan_dui.animetaste)
[Auro](https://play.google.com/store/apps/details?id=com.architjn.acjmusicplayer)
are not available on play store.
The links are incorrect.

**Comment by pcqpcq** [comment]
fixed with #145 , thanks to @ReadmeCritic
