### ISSUE TITLE
Best category for Narrate

### ISSUE THREAD

**Issue by Hauwertlhaufn** [pcqpcq/open-source-android-apps#154]
Hi, I'm not shure which the best category for Narrate is. 
What would you say?
It is a small and simple journal.

https://github.com/timothymiko/narrate-android
https://play.google.com/store/apps/details?id=com.datonicgroup.narrate.app

**Comment by pcqpcq** [comment]
it's in LIFESTYLE at GooglePlay, we can create "LIFESTYLE" category for it.

**Comment by pcqpcq** [comment]
I've created it: https://github.com/pcqpcq/open-source-android-apps/blob/master/categories/life_style.md
:)

you can add Narrate now

**Comment by Hauwertlhaufn** [comment]
Thank you
