### ISSUE TITLE
New logo for PCQPCQ

### ISSUE THREAD

**Issue by omamboo** [pcqpcq/open-source-android-apps#270]
I wanted to contribute to Pcqpcq. I designed a logo for pcqpcq. If you like it, I'll send you files and pr.

![pcqpcq](https://user-images.githubusercontent.com/38097218/38354711-bd7820ca-38e4-11e8-8663-984fa205f112.png)

Which one do you prefer?

**Comment by omamboo** [comment]
How about this?

![pcqpcq 2](https://user-images.githubusercontent.com/38097218/38355212-6d08e4f6-38e6-11e8-888b-e37e1b25ace7.png)

or what color do you like?

**Comment by mpreetam** [comment]
this is better

**Comment by omamboo** [comment]
so, you accept the logo proposal I submitted?

**Comment by mpreetam** [comment]
Yes Sir !

**Comment by omamboo** [comment]
I will send file cdr, pdf and png.

**Comment by pcqpcq** [comment]
THANK YOU SO MUCH!!!

But the origin logo has a deep meaning for me, sorry...
