### ISSUE TITLE
ios

### ISSUE THREAD

**Issue by xu6148152** [pcqpcq/open-source-android-apps#37]
Can we add ios open source app for this repository?

**Comment by pcqpcq** [comment]
There is already one project for iOS, check out [here](https://github.com/dkhamsing/open-source-ios-apps) by @dkhamsing

**Comment by dkhamsing** [comment]
:smile:

**Comment by xu6148152** [comment]
That repository is disorder, I think our repository is classified orderly.
So we can add ios column for this repository

**Comment by pcqpcq** [comment]
@dkhamsing What do you think about this? :joy:  

@xu6148152 : @dkhamsing is the author of that repository, maybe we can  make a suggestion...

In my opinion, I don't want to `"Reinventing the wheel." `, unless it is necessary to.

**Comment by dkhamsing** [comment]
Yea you could say it is not as organized but it's also simpler.. I'm not sure all the information should be in the same repo :confused:

**Comment by xu6148152** [comment]
ok.

**Comment by dkhamsing** [comment]
https://github.com/dkhamsing/open-source-ios-apps was updated, slightly improved

**Comment by pcqpcq** [comment]
nice! :+1:
