### ISSUE TITLE
Add UpgradeAll

### ISSUE THREAD

**Issue by momobobe** [pcqpcq/open-source-android-apps#370]
[UpgradeAll](https://github.com/DUpdateSystem/UpgradeAll) [[F-Droid](https://f-droid.org/packages/net.xzos.upgradeall/)]

UpgradeAll is a free and open source software which simplifies the process of finding updates for Android apps (even if you didn't install them), Magisk modules and more.

**Comment by pluwen** [comment]
Please create an PR
