### ISSUE TITLE
Definition of Categories

### ISSUE THREAD

**Issue by androchentw** [pcqpcq/open-source-android-apps#42]
May we have some definitions/keywords for each category?
Since I'm considering adding a messaging app, I got a little bit confused between "social network" & "communication".
Is there any good way to determine which category should an app belong to? (beside looking at what has been added in the category)
I think this would benefit both fresh user and contributor.

**Comment by pcqpcq** [comment]
Oh, it's my fault, sorry. I didn't say clear.  
I usually according to its category in GooglePlay. 

But if it's not in GooglePlay...
well...what do you suggest?

**Comment by androchentw** [comment]
I guess Google Play category is somewhat not so appropriate since [Odoo Messaging](https://play.google.com/store/apps/details?id=com.odoo) is categorised as Business, while I think it's more like "Messaging" or social network is fine but not precise enough.

Actually I don't have idea good enough for categorising these apps... The only thing I know is that it's important for users to **search for the proper app** within this repo, and even could **compare** between several similar but different open-source app.

Using Google Play category could be a normalised way for contributors to know where to add apps, while it's way too ambiguous for me.

Guess we could reference other library like [Android Arsenal](https://android-arsenal.com/) to see how they deal with this problem.

**Comment by pcqpcq** [comment]
Yup, you are right!
I'll make a demo in dev branch, let's check it out later

**Comment by pcqpcq** [comment]
I didn't fiind anything useful from Android Arsenal. I didn't even find open-source apps there...what a pity...

so I made a change with what we talked above.
I think it's much better now , check out [the dev branch](https://github.com/pcqpcq/open-source-android-apps/tree/dev).
what do you think?

**Comment by androchentw** [comment]
Sorted in alphabetic manner, I like it!
And actually I think it's fine to categorise like this now, because you will examine every pull request whenever there is a new repo to come in.
So, as long as you're sticking to the same principle in categorising repos, it's easy for users to find where the wanted repo is.
Let's get it work for a while to see what else could be improved.
Thank you for your contribution!

**Comment by pcqpcq** [comment]
Yup! :smile:
