### ISSUE TITLE
AwesomeOpenSource

### ISSUE THREAD

**Issue by jeffreyjackson** [pcqpcq/open-source-android-apps#46]
@pcqpcq - we are creating a GitHub organization for open-source projects.  

We're moving everything here.
https://github.com/AwesomeOpenSource/

I've started mac-apps.  @dkhamsing is going to lead ios-apps and move to the org.  

Would you like to join?

**Comment by pcqpcq** [comment]
Oh, yes, of cause!
Thanks for inviting me! :smile:

**Comment by jeffreyjackson** [comment]
I'll add you as an admin to the /AwesomeOpenSource organization. You can transfer the repo here

https://github.com/pcqpcq/open-source-android-apps/settings#transfer_confirm

**Comment by pcqpcq** [comment]
It will have an influence on the forks, I need to check carefully

**Comment by jeffreyjackson** [comment]
Forks are not effected.  Take a look here 

https://help.github.com/articles/transferring-a-repository/

**Comment by pcqpcq** [comment]
Yup, I have read this, and I am thinking about this
> Keep in mind that users who have forked your repository will need to update their remote URLs to point to the new Git repository in order to continue opening pull requests.


Btw, I am just a member of the org, not an owner?
And there is an Android team(but no iOS team, for now), why, do you think we need this?

**Comment by jeffreyjackson** [comment]
@dkhamsing is moving the iOS repo over.  You are an admin to your repo

**Comment by jeffreyjackson** [comment]
The links on GitHub will continue to work.  They will only need to update their remote forks on their local machine

**Comment by jeffreyjackson** [comment]
@pcqpcq I'm creating an iOS team.  The teams are nice to have because we can group off who has access to which repos. For example, you'll be an admin for android.  if you have other github users you would be comfortable with merging pull requests then we can add them to that team.

**Comment by jeffreyjackson** [comment]
@pcqpcq will you be making the switch soon? cc @dkhamsing what about you?  I think someone needs to make the first move to help break the ice with other awesome owners.

**Comment by pcqpcq** [comment]
1. I do think it is a good idea to do what we want with a organization.
2. I think the problem what @dkhamsing and I are concerning should be the same. In fact, I wonder what does @dkhamsing think?

**Comment by dkhamsing** [comment]
I think it's a great place for new projects.. I'm still pondering moving my own.

**Comment by plojoki1187** [comment]
I think that we should discuss it over lunch, on a beach somewhere. We can
surely find the solution if we mull it over during a relaxing sunset.

**Comment by dkhamsing** [comment]
> We'll have a lot of nights like this.
> Making plans, very little sleep. 

Frank Underwood

**Comment by plojoki1187** [comment]
I think Android is the way to go. Desktop applications demand a iostream,
but mobile wise, android is much more streamlined for the novice savant's.

**Comment by dkhamsing** [comment]
¯\_(ツ)_/¯

**Comment by pcqpcq** [comment]
What if we just make a fork?

**Comment by jeffreyjackson** [comment]
i think a fork would work, and satisfy the purpose of the organization.  I'm not sure if the individuals gain any benefit from it though otherwise?  what happens if the fork gains traction over the original?  just thinking out loud :bikini: :shell: :fish: :tropical_drink: :tropical_fish:

**Comment by pcqpcq** [comment]
1. Check out the [lastfm-android](https://github.com/lastfm/lastfm-android) repo from lastfm org. , and you can find out what will happen. 
2. The benefit...I think it do is different. In my opinion, I am not thinking about "benefit" , I am still thinking about if I need to move it? Is there any other way to fit our purpose? (I do believe that we all want to do the good things :smile: ) I think "fork" Wayne a good idea, I will do it .
3. Do you think "issue" is a good place to talk about this? Maybe we can do it in Hangout or [gitter](https://gitter.im/)? Just thinking :smile:

**Comment by dkhamsing** [comment]
From @jeffreyjackson 
> Instead of forking, let's create a list that point back to everyone else.
> In the case that a repo becomes unsupported we can fork it at that time.

> what do you think? This should satisfy the majority of everyone's concern.

**Comment by plojoki1187** [comment]
@jeffereyjackson I think that sounds like a perfect plan. All aspects of a
repo are should be presented in a matter that is not confusing to others.

**Comment by pcqpcq** [comment]
nice.
but what's the different with this : https://github.com/sindresorhus/awesome

**Comment by pcqpcq** [comment]
what is the origin purpose of our org. ? 
why do we need to create this org. ?
is people need one, or for other reason?

**Comment by plojoki1187** [comment]
Intellius

¯_(ツ)_/¯

—
Reply to this email directly or view it on GitHub
<https://github.com/pcqpcq/open-source-android-apps/issues/46#issuecomment-90957684>
.

**Comment by plojoki1187** [comment]
I do think it is a good idea to do what we want with a organization.
On Apr 8, 2015 11:35 AM, "Joker" <notifications@github.com> wrote:
>
> I do think it is a good idea to do what we want with a organization.
> I think the problem what @dkhamsing and I are concerning should be the
same. In fact, I wonder what does @dkhamsing think?

**Comment by dkhamsing** [comment]
uh looks like repos will stay where they are
