### ISSUE TITLE
Add Libregamewiki entries

### ISSUE THREAD

**Issue by nicolasrpmaia** [pcqpcq/open-source-android-apps#58]
A quick search for "Android" on the Libre Game Wiki shows some FOSS games that have been ported to Android: 

https://libregamewiki.org/index.php?search=Android&title=Special%3ASearch&go=Go

Note that the ports themselves might not be free software, however.

**Comment by pcqpcq** [comment]
Thanks! I'll check it out later :smile:

**Comment by pcqpcq** [comment]
I take some games from libregamewiki, you can check this commit:  https://github.com/pcqpcq/open-source-android-apps/commit/bee17cadbda9ab115c4de48f99a48c37ea890d3e

**Comment by nicolasrpmaia** [comment]
No problem! :)
